"""empty message

Revision ID: 02f647a38fef
Revises: 725e849de08c
Create Date: 2023-11-21 15:31:48.095336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f647a38fef'
down_revision = '725e849de08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phonenumber', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])  # Navn gitt til constraint
        batch_op.create_unique_constraint('uq_users_phonenumber', ['phonenumber'])  # Navn gitt til constraint
        batch_op.drop_column('Id')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('firstName')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('Id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('phonenumber')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('id')

    op.drop_table('booking')
    # ### end Alembic commands ###
